on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'poetry'
    - run: poetry install
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: poetry run pre-commit run -a
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: poetry run pytest
